### ISSUE TITLE
When will cyborg be open-source?

### ISSUE THREAD

**Issue by Joe-zsc** [Jjschwartz/NetworkAttackSimulator#19]
I am looking forward to cyborg (https://arxiv.org/abs/2002.10667) being open-source。

**Comment by Jjschwartz** [comment]
Hey JoeJoe, I'm no longer involved in the Cyborg project so am not sure when or if it will become open source. However, the research organization developing Cyborg recently published a workshop paper (https://arxiv.org/abs/2108.09118) on Cyborg, you could try reaching out to the authors and see what their plans are for open-sourcing or if you can get access.

**Comment by Tudyx** [comment]
CybORG is open source now https://github.com/cage-challenge/CybORG
