### ISSUE TITLE
About the “DQN” agent and the "small" scenario

### ISSUE THREAD

**Issue by Joe-zsc** [Jjschwartz/NetworkAttackSimulator#3]
the dqn agent algorithm seems divergent when I run `dqn_agent.py small`
![1](https://user-images.githubusercontent.com/51767345/105273775-e818cb00-5bd6-11eb-9914-53c49a8cdfec.PNG)

I have tried many times. it seems like that when the training_steps>8k, the episode_return declines sharply.
![2](https://user-images.githubusercontent.com/51767345/105274281-d4219900-5bd7-11eb-8c6c-49f3c3451092.PNG)

**Comment by Yin-yue6** [comment]
I'm a beginner, and I'm also encountering issues with training the PT model in this small scenario. Could you please tell me how to resolve this problem? Were you able to successfully train a usable PT model?
