### ISSUE TITLE
Incomplete display of action result

### ISSUE THREAD

**Issue by rzvnbr** [Jjschwartz/NetworkAttackSimulator#35]
Hi,
Thank you for developing NASim, we have recently starting using it and find it very useful.
While using NASim, I noticed a minor issue with how the result of an action is displayed. In the file `action.py`, the function `ActionResult.info()` defines a dictionary from which the field `undefined_error` is missing. This causes the `__str__()` function to omit this field when displaying the action result.
To fix this issue I think that simply adding the code `undefined_error=self.undefined_error,` at line 649 in the file `action.py` should be enough.
Best wishes,
Razvan

**Comment by Jjschwartz** [comment]
Fixed in the version 0.11.0 release
